import { heroImage } from "../../ui/src/assets";

export const brandingSchema = {
  brandName: "Omkar Agencies",
  logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAiiod4PVQrDsuJpzsEtcFSG-R77GFKDCRwA&s",

  hero: {
    title: "Smart Logistics & Supply Chain Solutions",
    subtitle:
      "We deliver fast, reliable, and scalable logistics solutions tailored for modern businesses.",
    image: heroImage,
  },

  socialLinks: [
    {
      id: 1,
      title: "Facebook",
      link: "https://facebook.com",
      icon: "Facebook",
    },
    {
      id: 2,
      title: "Instagram",
      link: "https://instagram.com",
      icon: "Instagram",
    },
    { id: 3, title: "Twitter", link: "https://twitter.com", icon: "Twitter" },
  ],

  branches: {
    headOffice: {
      name: "Yogesh",
      address: "242 Ramamandira Street, Halaguru",
      city: "Halaguru",
      state: "Karnataka",
      postalCode: "571421",
      country: "IN",
    },
    subBranches: [
      {
        city: "Coimbatore",
        address: "No 3/204, G-Kulathur Road, Neelambur",
        state: "Tamil Nadu",
        postalCode: "641062",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        emails: ["example@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        city: "coimbatore",
        line1:
          "No 3/204,G-Kulathur Road,Neelambur, Venkitapuram,Chinniyampalayam",
        line2: "ramamdirastreet coimbatore",
        state: "tamilnadu",
        postalCode: "641062",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        name: "yogesh",
        line1: "242 ramamandirasteet ",
        line1: "ramamdirastreet halaguru",
        state: "karnataka",
        city: "halaguru",
        postalCode: "571421",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        city: "coimbatore",
        line1:
          "No 3/204,G-Kulathur Road,Neelambur, Venkitapuram,Chinniyampalayam",
        line1: "ramamdirastreet coimbatore",
        state: "tamilnadu",
        postalCode: "641062",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        name: "yogesh",
        line1: "242 ramamandirasteet ",
        line1: "ramamdirastreet halaguru",
        state: "karnataka",
        city: "halaguru",
        postalCode: "571421",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        city: "coimbatore",
        line1:
          "No 3/204,G-Kulathur Road,Neelambur, Venkitapuram,Chinniyampalayam",
        line1: "ramamdirastreet coimbatore",
        state: "tamilnadu",
        postalCode: "641062",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
      {
        name: "yogesh",
        line1: "242 ramamandirasteet ",
        line1: "ramamdirastreet halaguru",
        state: "karnataka",
        city: "halaguru",
        postalCode: "571421",
        countrycode: "IN",
        statecode: "",
        contacts: ["xxxxxxxxx", "xxxxxxxxx"],
        email: ["exammple@gmail.com", "exammple@gmail.com"],
        gstNo: "33AAAAA0000A1Z5",
        igst: "33AAAAA0000A1Z5",
      },
    ],
  },
};
