export const AUTH_ROUTES = {
  HOME: 'home',
  ABOUT: 'about',
  CONTACT: 'contact',
  SERVICE: 'services',
  LOGIN: 'login',
  SIGNUP: 'signup',
  CAREER: 'careers',
  BLOG: 'blog',
  PRIVACY: 'privacy',
  TERM: 'terms',
  AUTH: 'auth',
  ROAD: 'road',
  OCEAN: 'ocean',
  AIR: 'air',
  WAREHOUSE: 'warehouse',
  EXPRESS: 'express',
  SUPLYCHAIN: 'suply-chain',
};
